name: Count Lines of Code of This Repository
description: 'This action counts the lines of code of this repository.'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - shell: bash
      run: |
        export FORMAT=default
        ./scripts/cloc-repository.sh
