# See:
# - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
# - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms


name: 🐞 Support Request
description: Get help
labels: ["support"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a support request. Please fill out this form as completely as possible.
  - type: textarea
    attributes:
      label: What exactly are you trying to do?
      description: Describe in as much detail as possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What have you tried so far?
      description: Describe what you have tried so far.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Where else have you checked for a solution?
      placeholder: |
        * [ ] I have read [user guide](./user-guide.md), and not found the answer.
        * [ ] I have searched [project documentation](./project-documentation.html), and not found the answer.
        * [ ] Other, please give details.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Output of any commands you have tried
      description: Please copy and paste any relevant output. This will be automatically formatted into codeblock.
      render: Shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: true
