name: "Scan Secrets"
description: "Scan Secrets"
runs:
  using: "composite"
  steps:
    - name: "Checkout code"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Full history is needed to scan all commits
    - name: "Scan Secrets"
      shell: bash
      run: |
        export ALL_FILES=true
        ./scripts/githooks/scan-secrets.sh
