name: Check File Format
description: "This action checks the file format of the files in the repository."
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - shell: bash
      run: |
        export BRANCH_NAME=origin/${{ github.event.repository.default_branch }}
        ./scripts/githooks/editorconfig-pre-commit.sh
