name: Check Markdown Format
description: 'This action checks the Markdown format of the files in the repository.'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - shell: bash
      run: |
        export BRANCH_NAME=origin/${{ github.event.repository.default_branch }}
        ./scripts/githooks/markdown-pre-commit.sh
