name: "Check Markdown Format"
description: "Check Markdown Format"
runs:
  using: "composite"
  steps:
    - name: "Checkout code"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Full history is needed for git diff
    - name: "Check File Format"
      shell: bash
      run: |
        export BRANCH_NAME=origin/${{ github.event.repository.default_branch }}
        ./scripts/githooks/check-markdown-format.sh
