name: CI/CD Pipeline Pull Request

on:
  push:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  cicd-pipeline-check:
    uses: ./.github/workflows/cicd-pipeline-check.yaml
  build-stage:
    runs-on: ubuntu-latest
    needs: [cicd-pipeline-check]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: List Variables
        run: |
          export BUILD_DATETIME="${{ needs.cicd-pipeline-check.outputs.build_datetime }}"
          export BUILD_TIMESTAMP="${{ needs.cicd-pipeline-check.outputs.build_timestamp }}"
          export BUILD_EPOCH="${{ needs.cicd-pipeline-check.outputs.build_epoch }}"
          export VERSION="${{ needs.cicd-pipeline-check.outputs.version }}"
          make list-variables
      # - name: Build ...
      #   run: |
      #     ?
