name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      build_datetime: ${{ steps.metadata.outputs.build_datetime }}
      build_timestamp: ${{ steps.metadata.outputs.build_timestamp }}
      build_epoch: ${{ steps.metadata.outputs.build_epoch }}
      version: ${{ steps.metadata.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - id: metadata
        run: |
          datetime=$(date -u +'%Y-%m-%dT%H:%M:%S%z')
          echo "build_datetime=$datetime" >> $GITHUB_OUTPUT
          echo "build_timestamp=$(date --date=$datetime -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "build_epoch=$(date --date=$datetime -u +'%s')" >> $GITHUB_OUTPUT
          echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
  commit-stage:
    needs: [metadata]
    uses: ./.github/workflows/stage-commit.yaml
  test-stage:
    needs: [metadata, commit-stage]
    uses: ./.github/workflows/stage-test.yaml
  build-stage:
    needs: [metadata, test-stage]
    uses: ./.github/workflows/stage-build.yaml
  cicd-pipeline:
    runs-on: ubuntu-latest
    needs: [metadata, build-stage]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: List Variables
        run: |
          export BUILD_DATETIME="${{ needs.metadata.outputs.build_datetime }}"
          export BUILD_TIMESTAMP="${{ needs.metadata.outputs.build_timestamp }}"
          export BUILD_EPOCH="${{ needs.metadata.outputs.build_epoch }}"
          export VERSION="${{ needs.metadata.outputs.version }}"
          make list-variables
