name: CI/CD Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "This is the tag that is oging to be deployed"
        required: true
        default: "latest"

jobs:
  metadata:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      version: ${{ steps.variables.outputs.version }}
      tag: ${{ steps.variables.outputs.tag }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set CI/CD variables
        id: variables
        run: |
          echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
          echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
      - name: List variables
        run: |
          export VERSION="${{ steps.variables.outputs.version }}"
          export GIT_TAG="${{ steps.variables.outputs.tag }}"
          make list-variables
  deploy:
    runs-on: ubuntu-latest
    needs: [metadata]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: List Variables
        run: |
          export VERSION="${{ needs.metadata.outputs.version }}"
          export GIT_TAG="${{ needs.metadata.outputs.tag }}"
          make list-variables
  # TODO: More jobs or/and steps here
