name: Generate SBOM

on:
  workflow_call:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          ./scripts/sbom-generator.sh
      - uses: actions/upload-artifact@v3
        with:
          name: sbom-spdx.json
          path: ./sbom-spdx.json
      - uses: advanced-security/spdx-dependency-submission-action@v0.0.1
        #continue-on-error: true
        with:
          filePath: ./sbom-spdx.json
