name: "Check Terraform Format"

on:
  workflow_call:

jobs:
  check-terraform-format:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - run: |
          export CHECK_ONLY=true
          ./scripts/githooks/check-terraform-format.sh
