name: "Scan Secrets"

on:
  workflow_call:

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Full history is needed to scan all commits
      - run: |
          export ALL_FILES=true
          ./scripts/githooks/scan-secrets.sh
