name: Scan Dependencies

on:
  workflow_call:
    inputs:
      build_timestamp:
        description: "Build timestamp, set by the CI/CD pipeline workflow"
        required: true
        type: string

jobs:
  scan-dependencies:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Generate SBOM"
        run: ./scripts/generate-sbom.sh
      - name: "Upload SBOM report as an artefact"
        uses: actions/upload-artifact@v3
        with:
          name: sbom-report.json
          path: ./sbom-report.json
      - name: "Scan vulnerabilities"
        run: ./scripts/scan-vulnerabilities.sh
      - name: "Upload vulnerabilities report as an artefact"
        uses: actions/upload-artifact@v3
        with:
          name: vulnerabilities-report.json
          path: ./vulnerabilities-report.json
      - name: "Authenticate to send the reports"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.IDP_AWS_ACCOUNT_ID }}:role/${{ secrets.IDP_AWS_ROLE_NAME }}
          aws-region: ${{ secrets.IDP_AWS_REGION }}
      - name: "Send the SBOM and vulnerabilities report to the central location"
        run: |
          aws s3 cp ./sbom-report.json ${{ secrets.IDP_SBOM_BUCKET_ENDPOINT }}/sbom-report-${{ inputs.build_timestamp }}.json
          aws s3 cp ./vulnerabilities-report.json ${{ secrets.IDP_SBOM_BUCKET_ENDPOINT }}/vulnerabilities-report-${{ inputs.build_timestamp }}.json
