name: Scan CVE

on:
  workflow_call:

jobs:
  scan-cve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          ./scripts/cve-scanner.sh
      - uses: actions/upload-artifact@v3
        with:
          name: cve-scan.json
          path: ./cve-scan.json
