name: Secret Scan

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          export ALL_FILES=true
          ./scripts/githooks/secret-scan-pre-commit.sh
