name: Commit Stage

on:
  workflow_call:

jobs:
  scan-secrets:
    uses: ./.github/workflows/job-scan-secrets.yaml
  check-file-format:
    uses: ./.github/workflows/job-check-file-format.yaml
  check-markdown-format:
    uses: ./.github/workflows/job-check-markdown-format.yaml
  cloc-repository:
    uses: ./.github/workflows/job-cloc-repository.yaml
  scan-dependencies:
    uses: ./.github/workflows/job-scan-dependencies.yaml
