name: Build Stage

on:
  workflow_call:

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      build_datetime: ${{ steps.metadata.outputs.build_datetime }}
      build_timestamp: ${{ steps.metadata.outputs.build_timestamp }}
      build_epoch: ${{ steps.metadata.outputs.build_epoch }}
      version: ${{ steps.metadata.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - id: metadata
        run: |
          datetime=$(date -u +'%Y-%m-%dT%H:%M:%S%z')
          echo "build_datetime=$datetime" >> $GITHUB_OUTPUT
          echo "build_timestamp=$(date --date=$datetime -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "build_epoch=$(date --date=$datetime -u +'%s')" >> $GITHUB_OUTPUT
          echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

  artefact-1:
    runs-on: ubuntu-latest
    needs: [metadata]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: List variables
        run: |
          export BUILD_DATETIME="${{ needs.metadata.outputs.build_datetime }}"
          export BUILD_TIMESTAMP="${{ needs.metadata.outputs.build_timestamp }}"
          export BUILD_EPOCH="${{ needs.metadata.outputs.build_epoch }}"
          export VERSION="${{ needs.metadata.outputs.version }}"
          make list-variables
      - name: Build artefact 1
        run: |
          echo "Building artefact 1 ..."
      - name: Check artefact 1
        run: |
          echo "Checking artefact 1 ..."

  artefact-2:
    runs-on: ubuntu-latest
    needs: [metadata]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: List variables
        run: |
          export BUILD_DATETIME="${{ needs.metadata.outputs.build_datetime }}"
          export BUILD_TIMESTAMP="${{ needs.metadata.outputs.build_timestamp }}"
          export BUILD_EPOCH="${{ needs.metadata.outputs.build_epoch }}"
          export VERSION="${{ needs.metadata.outputs.version }}"
          make list-variables
      - name: Build artefact 2
        run: |
          echo "Building artefact 2 ..."
      - name: Check artefact 2
        run: |
          echo "Checking artefact 2 ..."
