name: Build Stage

on:
  workflow_call:
    inputs:
      build_datetime:
        description: "Build datetime"
        required: true
        type: string
      build_timestamp:
        description: "Build timestamp"
        required: true
        type: string
      build_epoch:
        description: "Build epoch"
        required: true
        type: string
      version:
        description: "Version of the software"
        required: true
        type: string

jobs:
  artefact-1:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: List variables
        run: |
          export BUILD_DATETIME="${{ inputs.build_datetime }}"
          export BUILD_TIMESTAMP="${{ inputs.build_timestamp }}"
          export BUILD_EPOCH="${{ inputs.build_epoch }}"
          export VERSION="${{ inputs.version }}"
          make list-variables
      - name: Build artefact 1
        run: |
          echo "Building artefact 1 ..."
      - name: Check artefact 1
        run: |
          echo "Checking artefact 1 ..."
  artefact-2:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: List variables
        run: |
          export BUILD_DATETIME="${{ inputs.build_datetime }}"
          export BUILD_TIMESTAMP="${{ inputs.build_timestamp }}"
          export BUILD_EPOCH="${{ inputs.build_epoch }}"
          export VERSION="${{ inputs.version }}"
          make list-variables
      - name: Build artefact 2
        run: |
          echo "Building artefact 2 ..."
      - name: Check artefact 2
        run: |
          echo "Checking artefact 2 ..."
